## Questions

  * Are Rhat / etc not applicable to variational inference (vi only has 1 chain always?)
  * internal functions structure bayesplot
    - inlcuding for making plot for SE mean
    - how to access them? 
    - how are they being used by bayesplot?
  * parallelCoordinates plot, slow but as first? 
  * maybe bring chains option into sidebar
    - than wellpanel could be inside of tabUI's for
        - divergences (single)
        - chainplot (multiple)
        - autocorrelation (multiple)
  




## Page Structures

### Homepage

Get a summary of all warnings on the homepage. 

### Diagnostics

Separate into HMC diagnostics and non-HMC diagnostics. Repeat modules arn't a problem.

HMC diagnostics:

* divergence transitions
* parallel coords plots
* Energy etc.
 
Non-HMC diagnostics:

* Rhat
* nEff
* ...

## Code structures

### What to work with?

Always assume that in the global environment you have a [shinystan object](https://cran.r-project.org/web/packages/shinystan/shinystan.pdf). All manipulations are done with respect to this object. 

### What to build with?

Throughout shinystan we will build all separate pieces using [moduels](https://shiny.rstudio.com/articles/modules.html).


